POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de FastAPI"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/58ddfbd5-defe-43de-b456-251136607868
